# Fichier : admin/config.yml
# VERSION CORRECTE (pour fonctionner sans SSG)

backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog" # Nom technique
    label: "Artigos do Blog" # Nom visible dans l'interface
    folder: "posts" # Il créera un dossier "posts" pour vos articles
    create: true
    slug: "{{slug}}" # Le nom du fichier sera basé sur le slug que vous entrez
    extension: "html" # Il créera des fichiers .html
    # PAS DE LIGNE format: ICI
    
    # Nous n'utilisons qu'UN SEUL champ : le corps HTML complet
    fields:
      - label: "Code HTML Complet de l'Article"
        name: "body"
        widget: "markdown" # Permet d'éditer le HTML
