# Fichier : admin/config.yml
# Version CORRIGÉE

# Indique à Netlify comment se connecter
backend:
  name: git-gateway
  branch: main # (ou "master" si votre branche principale s'appelle "master")

# Où stocker les images que vous uploadez depuis le CMS
media_folder: "images/uploads"
public_folder: "/images/uploads"

# La collection de vos articles
collections:
  - name: "blog" # Nom technique
    label: "Artigos do Blog" # Nom visible dans l'interface
    folder: "posts" # Il créera un dossier "posts" pour vos articles
    create: true
    slug: "{{slug}}" # Le nom du fichier sera basé sur le titre
    extension: "html" # Il créera des fichiers .html
    format: "frontmatter" # Il mettra les métadonnées en haut
    editor:
      preview: false
      
    # Ce sont les champs que vous verrez dans l'éditeur
    fields:
      - { label: "Titre de l'article", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image Principale", name: "thumbnail", widget: "image" }
      - { label: "Catégorie (ex: Softwares, IA)", name: "category", widget: "string" }
      - { label: "Corps de l'article", name: "body", widget: "markdown" }

    # C'EST LA PARTIE LA PLUS IMPORTANTE
    # C'est le "modèle" HTML que Decap utilisera pour CRÉER vos fichiers d'article
    # Je l'ai déplacé ici, au bon niveau d'indentation.
    body: |
      <!DOCTYPE html>
      <html lang="pt-BR">
      <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>{{title}} - TechBoost</title>
          
          <meta property="og:title" content="{{title}}">
          <meta property="og:image" content="{{thumbnail}}">
          
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
          
          <style>
            :root {
                --blue: #007bff;
                --violet: #7b2cbf;
                --light-gray: #f4f4f4;
                --dark-text: #222;
                --light-text: #f9f9f9;
                --bg-color: #ffffff;
                --card-bg: #ffffff;
                --header-bg: rgba(255, 255, 255, 0.95);
                --border-color: #e0e0e0;
                --shadow-color: rgba(0, 0, 0, 0.05);
                --gradient: linear-gradient(45deg, var(--blue), var(--violet));
            }
            [data-theme="dark"] {
                --light-gray: #2a2a2a;
                --dark-text: #f4f4f4;
                --light-text: #f9f9f9;
                --bg-color: #1a1a1a;
                --card-bg: #252525;
                --header-bg: rgba(25, 25, 25, 0.95);
                --border-color: #444;
                --shadow-color: rgba(0, 0, 0, 0.2);
            }
            *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
            body {
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
                background-color: var(--bg-color);
                color: var(--dark-text);
                line-height: 1.6;
                transition: background-color 0.3s ease, color 0.3s ease;
            }
            h1, h2, h3, h4 { font-weight: 700; color: var(--dark-text); }
            h1 { font-size: 2.5rem; }
            h2 { font-size: 2rem; margin-bottom: 1.5rem; }
            h3 { font-size: 1.25rem; margin: 0.5rem 0; }
            h4 { font-size: 1.3rem; }
            a { color: var(--blue); text-decoration: none; }
            img { max-width: 100%; height: auto; display: block; }
            section { padding: 4rem 5%; max-width: 1200px; margin: 0 auto; }
            header {
                background-color: var(--header-bg);
                border-bottom: 1px solid var(--border-color);
                padding: 1rem 5%;
                position: sticky;
                top: 0;
                z-index: 100;
                backdrop-filter: blur(10px);
            }
            nav {
                display: flex;
                justify-content: space-between;
                align-items: center;
                max-width: 1200px;
                margin: 0 auto;
            }
            .logo { font-size: 1.5rem; font-weight: 700; color: var(--dark-text); }
            .logo i { color: var(--blue); }
            .nav-links { display: flex; list-style: none; gap: 1.5rem; }
            .nav-links a { color: var(--dark-text); font-weight: 500; transition: color 0.2s ease; }
            .nav-links a:hover { color: var(--blue); }
            #darkModeToggle { background: none; border: none; color: var(--dark-text); font-size: 1.2rem; cursor: pointer; }
            #menu-toggle { display: none; background: none; border: none; color: var(--dark-text); font-size: 1.5rem; cursor: pointer; }
            footer {
                text-align: center;
                padding: 3rem 5%;
                margin-top: 2rem;
                background-color: var(--light-gray);
                border-top: 1px solid var(--border-color);
            }
            .social-links { margin-bottom: 1rem; }
            .social-links a { font-size: 1.8rem; color: var(--dark-text); margin: 0 0.75rem; transition: color 0.3s ease; }
            .social-links a:hover { color: var(--blue); }
            .footer-links { margin-bottom: 1rem; font-size: 0.9rem; opacity: 0.8; }
            .footer-links a { margin: 0 0.5rem; }

            /* STYLES SPÉCIFIQUES AUX ARTICLES (du modèle) */
            .article-container {
                max-width: 800px; 
                margin: 0 auto;
                padding: 2rem 5%;
            }
            .article-header {
                text-align: center;
                margin-bottom: 2rem;
                border-bottom: 1px solid var(--border-color);
                padding-bottom: 2rem;
            }
            .article-header h1 {
                font-size: 2.8rem;
                line-height: 1.2;
                margin-bottom: 1rem;
            }
            .article-meta {
                font-size: 0.9rem;
                color: var(--dark-text);
                opacity: 0.7;
            }
            .article-meta .category {
                font-weight: 700;
                color: var(--violet);
            }
            .article-featured-image {
                width: 100%;
                height: auto;
                max-height: 400px;
                object-fit: cover;
                border-radius: 12px;
                margin-bottom: 2rem;
            }
            .article-content {
                font-size: 1.15rem;
                line-height: 1.7;
            }
            .article-content p, 
            .article-content ul, 
            .article-content ol {
                margin-bottom: 1.5rem;
            }
            .article-content h2 {
                font-size: 1.8rem;
                color: var(--blue);
                margin-top: 2.5rem;
                margin-bottom: 1rem;
            }
            .article-content h3 {
                font-size: 1.4rem;
                margin-top: 2rem;
                margin-bottom: 1rem;
            }
            .article-content ul, 
            .article-content ol {
                padding-left: 1.5rem;
            }
            .article-content a {
                text-decoration: underline;
            }
            .article-content blockquote {
                margin: 2rem 0;
                padding: 1rem 1.5rem;
                background: var(--light-gray);
                border-left: 5px solid var(--blue);
                font-style: italic;
                opacity: 0.9;
            }
            .article-content img {
                border-radius: 8px;
                margin: 1.5rem 0;
            }
            
            /* STYLES RESPONSIVES */
            @media (max-width: 768px) {
                .nav-links {
                    display: none; position: absolute; top: 60px; right: 0; width: 100%;
                    background-color: var(--header-bg); flex-direction: column; align-items: center;
                    padding: 1rem 0; gap: 1.5rem; box-shadow: 0 10px 20px var(--shadow-color);
                    border-bottom: 1px solid var(--border-color);
                }
                .nav-links.active { display: flex; }
                #menu-toggle { display: block; }
                .article-header h1 { font-size: 2.2rem; }
                .article-content { font-size: 1.05rem; }
            }
          </style>

      </head>
      <body>
          <header>
            <nav>
              <a href="/index.html" class="logo"><i class="fa-solid fa-bolt"></i> TechBoost</a>
              <ul class="nav-links" id="nav-links">
                <li><a href="/categoria-software.html">Softwares</a></li>
                <li><a href="/categoria-ia.html">IA</a></li>
                <li><a href="/index.html#recursos">Recursos</a></li>
              </ul>
              <div>
                <button id="darkModeToggle" title="Mudar tema" aria-label="Alternar modo claro e escuro"><i class="fa-solid fa-moon"></i></button>
                <button id="menu-toggle" aria-label="Abrir menu"><i class="fa-solid fa-bars"></i></button>
              </div>
            </nav>
          </header>

          <main>
            <article class="article-container">
              <header class="article-header">
                <h1>{{title}}</h1>
                <div class="article-meta">
                  Publicado em <span class="category">{{category}}</span> 
                  por <strong>[Seu Nome]</strong> em <time datetime="{{date}}">{{date}}</time>
                </div>
              </header>
              
              <img src="{{public_folder}}/{{thumbnail}}" alt="{{title}}" class="article-featured-image">
              
              <section class="article-content">
                {{body}}
              </section>
            </article>
          </main>

          <footer>
            <div class="social-links">
              <a href="#" title="YouTube" aria-label="Visite nosso YouTube"><i class="fa-brands fa-youtube"></i></a>
              <a href="#" title="Instagram" aria-label="Visite nosso Instagram"><i class="fa-brands fa-instagram"></i></a>
              <a href="#" title="TikTok" aria-label="Visite nosso TikTok"><i class="fa-brands fa-tiktok"></i></a>
              <a href="#" title="LinkedIn" aria-label="Visite nosso LinkedIn"><i class="fa-brands fa-linkedin"></i></a>
              <a href="#" title="Twitter (X)" aria-label="Visite nosso Twitter"><i class="fa-brands fa-x-twitter"></i></a>
            </div>
            <p class="footer-links">
              <a href="/politica-privacidade.html">Política de Privacidade</a> | 
              <a href="/termos-uso.html">Termos de Uso</a> |
              <a href="/contato.html">Contato</a>
            </p>
            <p>&copy; 2025 TechBoost. Todos os direitos reservados.</p>
          </footer>
          
          <script>
            document.addEventListener('DOMContentLoaded', () => {
                
                /* ======== GESTIONNAIRE DU MODE SOMBRE ======== */
                const darkModeToggle = document.getElementById('darkModeToggle');
                const toggleIcon = darkModeToggle.querySelector('i');
                const htmlElement = document.documentElement;

                const applyTheme = (theme) => {
                    htmlElement.setAttribute('data-theme', theme);
                    if (theme === 'dark') {
                        toggleIcon.classList.remove('fa-moon');
                        toggleIcon.classList.add('fa-sun');
                    } else {
                        toggleIcon.classList.remove('fa-sun');
                        toggleIcon.classList.add('fa-moon');
                    }
                    localStorage.setItem('theme', theme);
                };

                const savedTheme = localStorage.getItem('theme');
                const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;

                let currentTheme;
                if (savedTheme) {
                    currentTheme = savedTheme;
                } else {
                    currentTheme = prefersDark ? 'dark' : 'light';
                }
                
                applyTheme(currentTheme);

                darkModeToggle.addEventListener('click', () => {
                    const newTheme = htmlElement.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
                    applyTheme(newTheme);
                });

                /* GESTIONNAIRE DU MENU MOBILE */
                const menuToggle = document.getElementById('menu-toggle');
                const navLinks = document.getElementById('nav-links');
                const menuToggleIcon = menuToggle.querySelector('i');

                menuToggle.addEventListener('click', () => {
                    navLinks.classList.toggle('active');

                    if (navLinks.classList.contains('active')) {
                        menuToggleIcon.classList.remove('fa-bars');
                        menuToggleIcon.classList.add('fa-xmark');
                        menuToggle.setAttribute('aria-label', 'Fechar menu');
                    } else {
                        menuToggleIcon.classList.remove('fa-xmark');
                        menuToggleIcon.classList.add('fa-bars');
                        menuToggle.setAttribute('aria-label', 'Abrir menu');
                    }
                });
            });
          </script>
      </body>
      </html>
